#!/usr/bin/env bash
# ssh config file


Host *
      PasswordAuthentication no
      IdentifyFile ~/.ssh/school
      SendEnv LANG LC_*
      HashKnownHoste yes
      GSSAPIAuthentication yes
      GSSAPIDelegateCredentials no
